### ISSUE TITLE
Cell with multi-line text does not work

### ISSUE THREAD

**Issue by ahmedxfn** [Evertras/bubble-table#93] opened 2022-06-07 16:30 UTC
How to implement a cell with multi-line ?

when I added a new line in text like `some text\n some other text`, it appeared like this `some text...`

**Comment by Evertras** [comment] 2022-06-07 23:39
This is currently by design, as there is no way to separate cells visually if they can span multiple lines.  I'm cautiously open to the idea, but it will take some work to solve.

**Comment by prgres** [comment] 2023-11-23 12:26
I did some dirty cell wrapping in the bubble.Table https://github.com/charmbracelet/bubbles/pull/433 but it does not respect words. I may do a POC with reflow usage - maybe something valuable will pop out

**Comment by Evertras** [comment] 2023-11-23 12:54
The other issue here is that there's no way to tell that "The first table entry, ever" and "This is a really, really..." are separate rows.  I'm not sure if that particular issue is solvable with this table setup by default.

**Comment by prgres** [comment] 2023-11-23 13:30
It will be more readable if the other cells in that row align to the top

**Comment by prgres** [comment] 2023-11-23 13:32
I have opened the PR https://github.com/Evertras/bubble-table/pull/159 let's move future conversation there

**Comment by prgres** [comment] 2023-11-24 12:05
In the PR I successfully implemented that but it needs a review regarding the regression in the proposed logic.

**Comment by Evertras** [comment] 2023-11-26 04:59
Released as v0.15.6, thanks to @prgres for the work here!  It's been a while so I'll close this one myself, but feel free to reopen or create a new issue if there's more to do here.

**Closed by Evertras** 2023-11-26 04:59 UTC
Labels: enhancement
